export let DEFAULT_ITEMS=[{
      id: "001",
    image: `${import.meta.env.BASE_URL}images/1.jpg`,
    company: "Carlton London",
    item_name: "Rhodium-Plated CZ Floral Studs",
    original_price: 1045,
    current_price: 606,
    discount_price: 606,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: "10 oct 2023",
    rating: {
      stars: 4.5,
      count: 1400,
    },
  },

  {
    id: "002",
    image: "/images/2.jpg",
    company: "CUKOO",
    item_name: "Women Padded Halter Neck Swimmi...",
    original_price: 2599,
    current_price: 1507,
    discount_price: 1507,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: "10 oct 2023",
    rating: {
      stars: 4.5,
      count: 24,
    },
  },


  {
         id: "003",
    image: "/images/3.jpg",
    company: "NUEVOSDAMAS",
    item_name: "Women Red & White Printed A-Line...",
    original_price: 1699,
    current_price: 495,
    discount_price: 495,
    discount_percentage: 69,
    return_period: 14,
    delivery_date: "10 oct 2023",
    rating: {
      stars: 4.1,
      count: 1245,
    },
  },


  {
        id: "004",
    image: "/images/4.jpg",
    company: "ADIDAS",
    item_name: "Indian Cricket ODI Jerse ...",
    original_price: 999,
    current_price: 999,
    discount_price: 999,
    discount_percentage: 0,
    return_period: 14,
    delivery_date: "10 oct 2023",
    rating: {
      stars: 4.1,
      count: 2564,
    },
  },

   {
         id: "005",
    image: "/images/5.jpg",
    company: "Roadster",
    item_name: "Pure Cotton T-Shirt",
    original_price: 1399,
    current_price: 489,
    discount_price: 489,
    discount_percentage: 65,
    return_period: 14,
    delivery_date: "10 oct 2023",
    rating: {
      stars: 4.8,
      count: 1480,
    },
   },

   {
         id: "006",
    image: "/images/6.jpg",
    company: "Nike",
    item_name: "Men Running Shoes",
    original_price: 14995,
    current_price: 14995,
    discount_price: 14995,
    discount_percentage: 0,
    return_period: 14,
    delivery_date: "10 oct 2023",
    rating: {
      stars: 4.9,
      count: 1256,
    },
   },

   {
         id: "007",
    image: "/images/7.jpg",
    company: "The Indian Garage Co",
    item_name: "Men Slim Fit Regular Shorts",
    original_price: 1699,
    current_price: 639,
    discount_price: 639,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: "10 oct 2023",
    rating: {
      stars: 4.9,
      count: 1458,
    },
   },

   {
         id: "008",
    image: "/images/8.jpg",
    company: "Nivea",
    item_name: "Men Fresh Deodrant 150ml",
    original_price: 285,
    current_price: 142,
    discount_price: 142,
    discount_percentage: 50,
    return_period: 14,
    delivery_date: "10 oct 2023",
    rating: {
      stars: 4.1,
      count: 5200,
    },
   },
]
